var scripts = [
//    {name: "ap_calc", events: ["frame_load", "click"], match: ["http://warchaos.ru/f/a"], desc: "Подсчёт ходов"},
//    {name: "boiler", events: ["load", "frame_load", "click"], match: ["http://warchaos.ru/f/a"], desc: "Варка зелий"},
//    {name: "buildings", events: ["load"], match: ["http://warchaos.ru/f/a"], desc: "Здания"},
//    {name: "buy_force", events: [], match: ["http://warchaos.ru/f/a"], libraries: ["jquery-ui"], desc: "Покупка войск"},
//    {name: "icon_replacer", events: ["frame_load", "click", "load"], match: ["http://warchaos.ru/*"], desc: "Замена иконок"},
//    {name: "loot_button", events: ["frame_load", "click"], match: ["http://warchaos.ru/f/a"], libraries: ["jquery-ui"], desc: "Кнопки для лута"},
    {name: "main_menu", events: ["load"], match: ["http://warchaos.ru/*"], libraries: ["jquery-ui"], desc: "Ссылки в главном меню, индикаторы зелий"},
//    {name: "mandragora", events: ["click"], match: ["http://warchaos.ru/f/a"], desc: "Сборка мандрагоры"},
    {name: "mapper_shaz", events: [], match: ["http://warchaos.ru/*"], desc: "Маппер"},
//    {name: "mapper_sender_shaz", events: [], match: ["http://dragonmap.ru/thispageshouldneverexist"], desc: "Маппер сендер"},
//    {name: "marker", events: ["load"], match: ["http://warchaos.ru/f/a"], desc: "Маркер(25ч., для сокланов)"},
//    {name: "replace_force_size", events: ["frame_load", "click", "load"], match: ["http://warchaos.ru/f/a", "http://warchaos.ru/snapshot/*", "http://warchaos.ru/~snapshot/*"], desc: "Замена словесных обозначений войск на числовые"},
//    {name: "safe_names", events: ["frame_load", "click", "load"], match: ["http://warchaos.ru/f/a"], desc: "Добавляет имена сейфам"},
//    {name: "wc_astar", events: [], match: ["http://warchaos.ru/f/a"], desc: "Астар. Двигалка юнитов"},
//    {name: "wc_market", events: ["load"], match: ["http://warchaos.ru/f/a"], libraries: ["jquery-ui", "underscore"], desc: "Рынок"},
];
