var scripts = [
    {name: "ap_calc", events: ["frame_load", "click"], match: ["http://warchaos.ru/f/a"]},
    {name: "boiler", events: ["load", "frame_load", "click"], match: ["http://warchaos.ru/f/a"]},
    {name: "buildings", events: ["load"], match: ["http://warchaos.ru/f/a"]},
//    {name: "buy_force", events: [], match: ["http://warchaos.ru/f/a"], libraries: ["jquery-ui"]},
    {name: "icon_replacer", events: ["frame_load", "click", "load"], match: ["http://warchaos.ru/*"]},
//    {name: "loot_button", events: ["frame_load", "click"], match: ["http://warchaos.ru/f/a"], libraries: ["jquery-ui"]},
    {name: "main_menu", events: ["load"], match: ["http://warchaos.ru/*"], libraries: ["jquery-ui"]},
    {name: "mandragora", events: ["click"], match: ["http://warchaos.ru/f/a"]},
//    {name: "mapper_shaz", events: [], match: ["http://warchaos.ru/*", "http://dragonmap.ru/thispageshouldneverexist"]},
    {name: "marker", events: ["load"], match: ["http://warchaos.ru/f/a"]},
    {name: "replace_force_size", events: ["frame_load", "click", "load"], match: ["http://warchaos.ru/f/a", "http://warchaos.ru/snapshot/*", "http://warchaos.ru/~snapshot/*"]},
    {name: "safe_names", events: ["frame_load", "click", "load"], match: ["http://warchaos.ru/f/a"]},
    {name: "wc_astar", events: [], match: ["http://warchaos.ru/f/a"]},
    {name: "wc_market", events: ["load"], match: ["http://warchaos.ru/f/a"], libraries: ["jquery-ui", "underscore"]},
];
